<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <parent>
    <groupId>com.aicas.osgi</groupId>
    <artifactId>service-loader</artifactId>
    <version>${revision}</version>
  </parent>
  <modelVersion>4.0.0</modelVersion>

  <groupId>com.aicas.osgi.example</groupId>
  <artifactId>example</artifactId>
  <name>ServiceLoader Examples</name>

  <packaging>pom</packaging>

  <modules>
    <module>serviceloader-consumer-metadata</module>
    <module>serviceloader-osgi-client</module>
    <module>serviceloader-provider-metadata</module>
    <module>serviceloader-consumer</module>
    <module>serviceloader-provider-fragment</module>
    <module>serviceloader-provider</module>
    <module>serviceloader-provider-moduleinfo</module>
    <module>serviceloader-spi</module>
  </modules>

</project>
